"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.argeo
  IDL file: argeo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds_types import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.argeo/1.7"
Time = types.typedef['spatialdds_types.spatial.argeo.Time', 'spatialdds_types.builtin.Time']
PoseSE3 = types.typedef['spatialdds_types.spatial.argeo.PoseSE3', 'spatialdds_types.spatial.core.PoseSE3']
FramedPose = types.typedef['spatialdds_types.spatial.argeo.FramedPose', 'spatialdds_types.spatial.core.FramedPose']
GeoPose = types.typedef['spatialdds_types.spatial.argeo.GeoPose', 'spatialdds_types.spatial.core.GeoPose']
CovMatrix = types.typedef['spatialdds_types.spatial.argeo.CovMatrix', 'spatialdds_types.spatial.core.CovMatrix']
FrameRef = types.typedef['spatialdds_types.spatial.argeo.FrameRef', 'spatialdds_types.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class NodeGeo(idl.IdlStruct, typename="spatial.argeo.NodeGeo"):
    map_id: str
    node_id: str
    annotate.key("node_id")
    poses: types.sequence['spatialdds_types.spatial.argeo.FramedPose', 8]
    has_geopose: bool
    geopose: 'spatialdds_types.spatial.argeo.GeoPose'
    source_id: str
    seq: types.uint64
    graph_epoch: types.uint64


