/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: discovery.h
  Source: /Users/fiberhog/AGENT_DEV/OARC/SpatialDDS-demo/idl/v1.7/discovery.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_DISCOVERY_H_C5F82BFF28C9568CB9C59C94E9C56659
#define DDSC_DISCOVERY_H_C5F82BFF28C9568CB9C59C94E9C56659

#include "core.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct spatial_common_MetaKV spatial_disco_MetaKV;

#define spatial_disco_MetaKV__alloc() \
((spatial_disco_MetaKV*) dds_alloc (sizeof (spatial_disco_MetaKV)));

typedef struct spatial_common_AssetRef spatial_disco_AssetRef;

#define spatial_disco_AssetRef__alloc() \
((spatial_disco_AssetRef*) dds_alloc (sizeof (spatial_disco_AssetRef)));

#define spatial_disco_MODULE_ID ("spatial.discovery/1.7")
typedef struct builtin_Time spatial_disco_Time;

#define spatial_disco_Time__alloc() \
((spatial_disco_Time*) dds_alloc (sizeof (spatial_disco_Time)));

typedef struct spatial_core_Aabb3 spatial_disco_Aabb3;

#define spatial_disco_Aabb3__alloc() \
((spatial_disco_Aabb3*) dds_alloc (sizeof (spatial_disco_Aabb3)));

typedef spatial_core_FrameRef spatial_disco_FrameRef;

#define spatial_disco_FrameRef__alloc() \
((spatial_disco_FrameRef*) dds_alloc (sizeof (spatial_disco_FrameRef)));

typedef struct spatial_core_PoseSE3 spatial_disco_PoseSE3;

#define spatial_disco_PoseSE3__alloc() \
((spatial_disco_PoseSE3*) dds_alloc (sizeof (spatial_disco_PoseSE3)));

typedef char *spatial_disco_SpatialUri;

#define spatial_disco_SpatialUri__alloc() \
((spatial_disco_SpatialUri*) dds_alloc (sizeof (spatial_disco_SpatialUri)));

typedef struct spatial_disco_ProfileSupport
{
  char * name;
  uint32_t major;
  uint32_t min_minor;
  uint32_t max_minor;
} spatial_disco_ProfileSupport;

extern const dds_topic_descriptor_t spatial_disco_ProfileSupport_desc;

#define spatial_disco_ProfileSupport__alloc() \
((spatial_disco_ProfileSupport*) dds_alloc (sizeof (spatial_disco_ProfileSupport)));

#define spatial_disco_ProfileSupport_free(d,o) \
dds_sample_free ((d), &spatial_disco_ProfileSupport_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_PROFILESUPPORT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_PROFILESUPPORT_DEFINED
typedef struct dds_sequence_spatial_disco_ProfileSupport
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_ProfileSupport *_buffer;
  bool _release;
} dds_sequence_spatial_disco_ProfileSupport;

#define dds_sequence_spatial_disco_ProfileSupport__alloc() \
((dds_sequence_spatial_disco_ProfileSupport*) dds_alloc (sizeof (dds_sequence_spatial_disco_ProfileSupport)));

#define dds_sequence_spatial_disco_ProfileSupport_allocbuf(l) \
((struct spatial_disco_ProfileSupport *) dds_alloc ((l) * sizeof (struct spatial_disco_ProfileSupport)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_PROFILESUPPORT_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct spatial_disco_Capabilities
{
  dds_sequence_spatial_disco_ProfileSupport supported_profiles;
  dds_sequence_string preferred_profiles;
  dds_sequence_string features;
} spatial_disco_Capabilities;

extern const dds_topic_descriptor_t spatial_disco_Capabilities_desc;

#define spatial_disco_Capabilities__alloc() \
((spatial_disco_Capabilities*) dds_alloc (sizeof (spatial_disco_Capabilities)));

#define spatial_disco_Capabilities_free(d,o) \
dds_sample_free ((d), &spatial_disco_Capabilities_desc, (o))

typedef struct spatial_disco_TopicMeta
{
  char * name;
  char * type;
  char * version;
  char * qos_profile;
  float target_rate_hz;
  uint32_t max_chunk_bytes;
} spatial_disco_TopicMeta;

extern const dds_topic_descriptor_t spatial_disco_TopicMeta_desc;

#define spatial_disco_TopicMeta__alloc() \
((spatial_disco_TopicMeta*) dds_alloc (sizeof (spatial_disco_TopicMeta)));

#define spatial_disco_TopicMeta_free(d,o) \
dds_sample_free ((d), &spatial_disco_TopicMeta_desc, (o))

typedef enum spatial_disco_ServiceKind
{
  spatial_disco_VPS,
  spatial_disco_MAPPING,
  spatial_disco_RELOCAL,
  spatial_disco_SEMANTICS,
  spatial_disco_STORAGE,
  spatial_disco_CONTENT,
  spatial_disco_ANCHOR_REGISTRY,
  spatial_disco_OTHER
} spatial_disco_ServiceKind;

#define spatial_disco_ServiceKind__alloc() \
((spatial_disco_ServiceKind*) dds_alloc (sizeof (spatial_disco_ServiceKind)));

typedef struct spatial_disco_KV
{
  char * key;
  char * value;
} spatial_disco_KV;

extern const dds_topic_descriptor_t spatial_disco_KV_desc;

#define spatial_disco_KV__alloc() \
((spatial_disco_KV*) dds_alloc (sizeof (spatial_disco_KV)));

#define spatial_disco_KV_free(d,o) \
dds_sample_free ((d), &spatial_disco_KV_desc, (o))

typedef struct spatial_disco_CoverageElement
{
  bool has_crs;
  char * crs;
  bool has_bbox;
  spatial_common_BBox2D bbox;
  bool has_aabb;
  spatial_disco_Aabb3 aabb;
  bool global;
  bool has_frame_ref;
  spatial_disco_FrameRef frame_ref;
  bool has_coverage_window;
  spatial_disco_Time coverage_window_start;
  spatial_disco_Time coverage_window_end;
} spatial_disco_CoverageElement;

extern const dds_topic_descriptor_t spatial_disco_CoverageElement_desc;

#define spatial_disco_CoverageElement__alloc() \
((spatial_disco_CoverageElement*) dds_alloc (sizeof (spatial_disco_CoverageElement)));

#define spatial_disco_CoverageElement_free(d,o) \
dds_sample_free ((d), &spatial_disco_CoverageElement_desc, (o))

typedef struct spatial_disco_ValidityWindow
{
  spatial_disco_Time from;
  uint32_t seconds;
} spatial_disco_ValidityWindow;

extern const dds_topic_descriptor_t spatial_disco_ValidityWindow_desc;

#define spatial_disco_ValidityWindow__alloc() \
((spatial_disco_ValidityWindow*) dds_alloc (sizeof (spatial_disco_ValidityWindow)));

#define spatial_disco_ValidityWindow_free(d,o) \
dds_sample_free ((d), &spatial_disco_ValidityWindow_desc, (o))

typedef struct spatial_disco_Transform
{
  spatial_disco_FrameRef from;
  spatial_disco_FrameRef to;
  spatial_disco_PoseSE3 pose;
  spatial_disco_Time stamp;
  bool has_validity;
  struct spatial_disco_ValidityWindow validity;
} spatial_disco_Transform;

extern const dds_topic_descriptor_t spatial_disco_Transform_desc;

#define spatial_disco_Transform__alloc() \
((spatial_disco_Transform*) dds_alloc (sizeof (spatial_disco_Transform)));

#define spatial_disco_Transform_free(d,o) \
dds_sample_free ((d), &spatial_disco_Transform_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_KV_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_KV_DEFINED
typedef struct dds_sequence_spatial_disco_KV
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_KV *_buffer;
  bool _release;
} dds_sequence_spatial_disco_KV;

#define dds_sequence_spatial_disco_KV__alloc() \
((dds_sequence_spatial_disco_KV*) dds_alloc (sizeof (dds_sequence_spatial_disco_KV)));

#define dds_sequence_spatial_disco_KV_allocbuf(l) \
((struct spatial_disco_KV *) dds_alloc ((l) * sizeof (struct spatial_disco_KV)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_KV_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_TOPICMETA_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_TOPICMETA_DEFINED
typedef struct dds_sequence_spatial_disco_TopicMeta
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_TopicMeta *_buffer;
  bool _release;
} dds_sequence_spatial_disco_TopicMeta;

#define dds_sequence_spatial_disco_TopicMeta__alloc() \
((dds_sequence_spatial_disco_TopicMeta*) dds_alloc (sizeof (dds_sequence_spatial_disco_TopicMeta)));

#define dds_sequence_spatial_disco_TopicMeta_allocbuf(l) \
((struct spatial_disco_TopicMeta *) dds_alloc ((l) * sizeof (struct spatial_disco_TopicMeta)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_TOPICMETA_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
typedef struct dds_sequence_spatial_disco_CoverageElement
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_CoverageElement *_buffer;
  bool _release;
} dds_sequence_spatial_disco_CoverageElement;

#define dds_sequence_spatial_disco_CoverageElement__alloc() \
((dds_sequence_spatial_disco_CoverageElement*) dds_alloc (sizeof (dds_sequence_spatial_disco_CoverageElement)));

#define dds_sequence_spatial_disco_CoverageElement_allocbuf(l) \
((struct spatial_disco_CoverageElement *) dds_alloc ((l) * sizeof (struct spatial_disco_CoverageElement)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
typedef struct dds_sequence_spatial_disco_Transform
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_Transform *_buffer;
  bool _release;
} dds_sequence_spatial_disco_Transform;

#define dds_sequence_spatial_disco_Transform__alloc() \
((dds_sequence_spatial_disco_Transform*) dds_alloc (sizeof (dds_sequence_spatial_disco_Transform)));

#define dds_sequence_spatial_disco_Transform_allocbuf(l) \
((struct spatial_disco_Transform *) dds_alloc ((l) * sizeof (struct spatial_disco_Transform)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED */

typedef struct spatial_disco_Announce
{
  char * service_id;
  char * name;
  spatial_disco_ServiceKind kind;
  char * version;
  char * org;
  dds_sequence_spatial_disco_KV hints;
  struct spatial_disco_Capabilities caps;
  dds_sequence_spatial_disco_TopicMeta topics;
  dds_sequence_spatial_disco_CoverageElement coverage;
  spatial_disco_FrameRef coverage_frame_ref;
  bool has_coverage_eval_time;
  spatial_disco_Time coverage_eval_time;
  dds_sequence_spatial_disco_Transform transforms;
  spatial_disco_SpatialUri manifest_uri;
  char * auth_hint;
  spatial_disco_Time stamp;
  uint32_t ttl_sec;
} spatial_disco_Announce;

extern const dds_topic_descriptor_t spatial_disco_Announce_desc;

#define spatial_disco_Announce__alloc() \
((spatial_disco_Announce*) dds_alloc (sizeof (spatial_disco_Announce)));

#define spatial_disco_Announce_free(d,o) \
dds_sample_free ((d), &spatial_disco_Announce_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
typedef struct dds_sequence_spatial_disco_CoverageElement
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_CoverageElement *_buffer;
  bool _release;
} dds_sequence_spatial_disco_CoverageElement;

#define dds_sequence_spatial_disco_CoverageElement__alloc() \
((dds_sequence_spatial_disco_CoverageElement*) dds_alloc (sizeof (dds_sequence_spatial_disco_CoverageElement)));

#define dds_sequence_spatial_disco_CoverageElement_allocbuf(l) \
((struct spatial_disco_CoverageElement *) dds_alloc ((l) * sizeof (struct spatial_disco_CoverageElement)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
typedef struct dds_sequence_spatial_disco_Transform
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_Transform *_buffer;
  bool _release;
} dds_sequence_spatial_disco_Transform;

#define dds_sequence_spatial_disco_Transform__alloc() \
((dds_sequence_spatial_disco_Transform*) dds_alloc (sizeof (dds_sequence_spatial_disco_Transform)));

#define dds_sequence_spatial_disco_Transform_allocbuf(l) \
((struct spatial_disco_Transform *) dds_alloc ((l) * sizeof (struct spatial_disco_Transform)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED */

typedef struct spatial_disco_CoverageHint
{
  char * service_id;
  dds_sequence_spatial_disco_CoverageElement coverage;
  spatial_disco_FrameRef coverage_frame_ref;
  bool has_coverage_eval_time;
  spatial_disco_Time coverage_eval_time;
  dds_sequence_spatial_disco_Transform transforms;
  spatial_disco_Time stamp;
  uint32_t ttl_sec;
} spatial_disco_CoverageHint;

extern const dds_topic_descriptor_t spatial_disco_CoverageHint_desc;

#define spatial_disco_CoverageHint__alloc() \
((spatial_disco_CoverageHint*) dds_alloc (sizeof (spatial_disco_CoverageHint)));

#define spatial_disco_CoverageHint_free(d,o) \
dds_sample_free ((d), &spatial_disco_CoverageHint_desc, (o))

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct spatial_disco_CoverageFilter
{
  dds_sequence_string type_in;
  dds_sequence_string qos_profile_in;
  dds_sequence_string module_id_in;
} spatial_disco_CoverageFilter;

extern const dds_topic_descriptor_t spatial_disco_CoverageFilter_desc;

#define spatial_disco_CoverageFilter__alloc() \
((spatial_disco_CoverageFilter*) dds_alloc (sizeof (spatial_disco_CoverageFilter)));

#define spatial_disco_CoverageFilter_free(d,o) \
dds_sample_free ((d), &spatial_disco_CoverageFilter_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
typedef struct dds_sequence_spatial_disco_CoverageElement
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_CoverageElement *_buffer;
  bool _release;
} dds_sequence_spatial_disco_CoverageElement;

#define dds_sequence_spatial_disco_CoverageElement__alloc() \
((dds_sequence_spatial_disco_CoverageElement*) dds_alloc (sizeof (dds_sequence_spatial_disco_CoverageElement)));

#define dds_sequence_spatial_disco_CoverageElement_allocbuf(l) \
((struct spatial_disco_CoverageElement *) dds_alloc ((l) * sizeof (struct spatial_disco_CoverageElement)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED */

typedef struct spatial_disco_CoverageQuery
{
  char * query_id;
  dds_sequence_spatial_disco_CoverageElement coverage;
  spatial_disco_FrameRef coverage_frame_ref;
  bool has_coverage_eval_time;
  spatial_disco_Time coverage_eval_time;
  bool has_filter;
  struct spatial_disco_CoverageFilter filter;
  char * reply_topic;
  spatial_disco_Time stamp;
  uint32_t ttl_sec;
} spatial_disco_CoverageQuery;

extern const dds_topic_descriptor_t spatial_disco_CoverageQuery_desc;

#define spatial_disco_CoverageQuery__alloc() \
((spatial_disco_CoverageQuery*) dds_alloc (sizeof (spatial_disco_CoverageQuery)));

#define spatial_disco_CoverageQuery_free(d,o) \
dds_sample_free ((d), &spatial_disco_CoverageQuery_desc, (o))

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
typedef struct dds_sequence_spatial_disco_CoverageElement
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_CoverageElement *_buffer;
  bool _release;
} dds_sequence_spatial_disco_CoverageElement;

#define dds_sequence_spatial_disco_CoverageElement__alloc() \
((dds_sequence_spatial_disco_CoverageElement*) dds_alloc (sizeof (dds_sequence_spatial_disco_CoverageElement)));

#define dds_sequence_spatial_disco_CoverageElement_allocbuf(l) \
((struct spatial_disco_CoverageElement *) dds_alloc ((l) * sizeof (struct spatial_disco_CoverageElement)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED */

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED
typedef struct dds_sequence_spatial_disco_Transform
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_Transform *_buffer;
  bool _release;
} dds_sequence_spatial_disco_Transform;

#define dds_sequence_spatial_disco_Transform__alloc() \
((dds_sequence_spatial_disco_Transform*) dds_alloc (sizeof (dds_sequence_spatial_disco_Transform)));

#define dds_sequence_spatial_disco_Transform_allocbuf(l) \
((struct spatial_disco_Transform *) dds_alloc ((l) * sizeof (struct spatial_disco_Transform)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_TRANSFORM_DEFINED */

typedef struct spatial_disco_ContentAnnounce
{
  char * content_id;
  char * provider_id;
  char * title;
  char * summary;
  dds_sequence_string tags;
  char * class_id;
  spatial_disco_SpatialUri manifest_uri;
  dds_sequence_spatial_disco_CoverageElement coverage;
  spatial_disco_FrameRef coverage_frame_ref;
  bool has_coverage_eval_time;
  spatial_disco_Time coverage_eval_time;
  dds_sequence_spatial_disco_Transform transforms;
  spatial_disco_Time available_from;
  spatial_disco_Time available_until;
  spatial_disco_Time stamp;
  uint32_t ttl_sec;
} spatial_disco_ContentAnnounce;

extern const dds_topic_descriptor_t spatial_disco_ContentAnnounce_desc;

#define spatial_disco_ContentAnnounce__alloc() \
((spatial_disco_ContentAnnounce*) dds_alloc (sizeof (spatial_disco_ContentAnnounce)));

#define spatial_disco_ContentAnnounce_free(d,o) \
dds_sample_free ((d), &spatial_disco_ContentAnnounce_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED
typedef struct dds_sequence_spatial_disco_CoverageElement
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_CoverageElement *_buffer;
  bool _release;
} dds_sequence_spatial_disco_CoverageElement;

#define dds_sequence_spatial_disco_CoverageElement__alloc() \
((dds_sequence_spatial_disco_CoverageElement*) dds_alloc (sizeof (dds_sequence_spatial_disco_CoverageElement)));

#define dds_sequence_spatial_disco_CoverageElement_allocbuf(l) \
((struct spatial_disco_CoverageElement *) dds_alloc ((l) * sizeof (struct spatial_disco_CoverageElement)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_COVERAGEELEMENT_DEFINED */

typedef struct spatial_disco_ServiceSummary
{
  char * service_id;
  spatial_disco_ServiceKind kind;
  char * name;
  spatial_disco_SpatialUri manifest_uri;
  dds_sequence_spatial_disco_CoverageElement coverage;
  spatial_disco_FrameRef coverage_frame_ref;
  spatial_disco_Time stamp;
  uint32_t ttl_sec;
} spatial_disco_ServiceSummary;

extern const dds_topic_descriptor_t spatial_disco_ServiceSummary_desc;

#define spatial_disco_ServiceSummary__alloc() \
((spatial_disco_ServiceSummary*) dds_alloc (sizeof (spatial_disco_ServiceSummary)));

#define spatial_disco_ServiceSummary_free(d,o) \
dds_sample_free ((d), &spatial_disco_ServiceSummary_desc, (o))

#ifndef DDS_SEQUENCE_SPATIAL_DISCO_SERVICESUMMARY_DEFINED
#define DDS_SEQUENCE_SPATIAL_DISCO_SERVICESUMMARY_DEFINED
typedef struct dds_sequence_spatial_disco_ServiceSummary
{
  uint32_t _maximum;
  uint32_t _length;
  struct spatial_disco_ServiceSummary *_buffer;
  bool _release;
} dds_sequence_spatial_disco_ServiceSummary;

#define dds_sequence_spatial_disco_ServiceSummary__alloc() \
((dds_sequence_spatial_disco_ServiceSummary*) dds_alloc (sizeof (dds_sequence_spatial_disco_ServiceSummary)));

#define dds_sequence_spatial_disco_ServiceSummary_allocbuf(l) \
((struct spatial_disco_ServiceSummary *) dds_alloc ((l) * sizeof (struct spatial_disco_ServiceSummary)))
#endif /* DDS_SEQUENCE_SPATIAL_DISCO_SERVICESUMMARY_DEFINED */

typedef struct spatial_disco_CoverageResponse
{
  char * query_id;
  dds_sequence_spatial_disco_ServiceSummary results;
  char * next_page_token;
} spatial_disco_CoverageResponse;

extern const dds_topic_descriptor_t spatial_disco_CoverageResponse_desc;

#define spatial_disco_CoverageResponse__alloc() \
((spatial_disco_CoverageResponse*) dds_alloc (sizeof (spatial_disco_CoverageResponse)));

#define spatial_disco_CoverageResponse_free(d,o) \
dds_sample_free ((d), &spatial_disco_CoverageResponse_desc, (o))

typedef struct spatial_disco_Depart
{
  char * service_id;
  spatial_disco_Time stamp;
} spatial_disco_Depart;

extern const dds_topic_descriptor_t spatial_disco_Depart_desc;

#define spatial_disco_Depart__alloc() \
((spatial_disco_Depart*) dds_alloc (sizeof (spatial_disco_Depart)));

#define spatial_disco_Depart_free(d,o) \
dds_sample_free ((d), &spatial_disco_Depart_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DISCOVERY_H_C5F82BFF28C9568CB9C59C94E9C56659 */
