// SPDX-License-Identifier: MIT
// SpatialDDS Convenience Aggregator (v1.4)
//
// The official v1.4 IDL lives under idl/v1.4/*.idl in this repository.
// This wrapper simply includes the individual profile files so existing
// build scripts that expect a single IDL can continue to function.

#include "idl/v1.4/types.idl"
#include "idl/v1.4/geometry.idl"
#include "idl/v1.4/common.idl"
#include "idl/v1.4/core.idl"
#include "idl/v1.4/discovery.idl"
#include "idl/v1.4/anchors.idl"
#include "idl/v1.4/vision.idl"
#include "idl/v1.4/vio.idl"
#include "idl/v1.4/slam_frontend.idl"
#include "idl/v1.4/argeo.idl"
#include "idl/v1.4/lidar.idl"
#include "idl/v1.4/rad.idl"
#include "idl/v1.4/semantics.idl"
