"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: spatial.semantics
  IDL file: semantics.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds_types import spatial

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "spatial.semantics/1.7"
Time = types.typedef['spatialdds_types.spatial.semantics.Time', 'spatialdds_types.builtin.Time']
TileKey = types.typedef['spatialdds_types.spatial.semantics.TileKey', 'spatialdds_types.spatial.core.TileKey']
FrameRef = types.typedef['spatialdds_types.spatial.semantics.FrameRef', 'spatialdds_types.spatial.common.FrameRef']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection2D(idl.IdlStruct, typename="spatial.semantics.Detection2D"):
    det_id: str
    annotate.key("det_id")
    node_id: str
    camera_id: str
    class_id: str
    score: types.float32
    bbox: 'spatialdds_types.spatial.common.BBox2D'
    has_mask: bool
    mask_blob_id: str
    stamp: 'spatialdds_types.spatial.semantics.Time'
    source_id: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection2DSet(idl.IdlStruct, typename="spatial.semantics.Detection2DSet"):
    set_id: str
    annotate.key("set_id")
    node_id: str
    camera_id: str
    dets: types.sequence['spatialdds_types.spatial.semantics.Detection2D', 256]
    stamp: 'spatialdds_types.spatial.semantics.Time'
    source_id: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection3D(idl.IdlStruct, typename="spatial.semantics.Detection3D"):
    det_id: str
    annotate.key("det_id")
    frame_ref: 'spatialdds_types.spatial.semantics.FrameRef'
    has_tile: bool
    tile_key: 'spatialdds_types.spatial.semantics.TileKey'
    class_id: str
    score: types.float32
    center: 'spatialdds_types.spatial.common.Vec3'
    size: 'spatialdds_types.spatial.common.Vec3'
    q: 'spatialdds_types.spatial.common.QuaternionXYZW'
    has_covariance: bool
    cov_pos: 'spatialdds_types.spatial.common.Mat3x3'
    cov_rot: 'spatialdds_types.spatial.common.Mat3x3'
    has_track_id: bool
    track_id: str
    stamp: 'spatialdds_types.spatial.semantics.Time'
    source_id: str
    has_attributes: bool
    attributes: types.sequence['spatialdds_types.spatial.common.MetaKV', 8]
    has_visibility: bool
    visibility: types.float32
    has_num_pts: bool
    num_lidar_pts: types.uint32
    num_radar_pts: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Detection3DSet(idl.IdlStruct, typename="spatial.semantics.Detection3DSet"):
    set_id: str
    annotate.key("set_id")
    frame_ref: 'spatialdds_types.spatial.semantics.FrameRef'
    has_tile: bool
    tile_key: 'spatialdds_types.spatial.semantics.TileKey'
    dets: types.sequence['spatialdds_types.spatial.semantics.Detection3D', 256]
    stamp: 'spatialdds_types.spatial.semantics.Time'
    source_id: str


