"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: oarc_demo
  IDL file: oarc_demo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds_idl import oarc_demo

if TYPE_CHECKING:
    import builtin


MODULE_ID = "oarc.demo/1.7"
Time = types.typedef['spatialdds_idl.oarc_demo.Time', 'spatialdds_idl.builtin.Time']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BootstrapQuery(idl.IdlStruct, typename="oarc_demo.BootstrapQuery"):
    client_id: str
    annotate.key("client_id")
    client_kind: str
    capabilities: types.sequence[str, 16]
    location_hint: str
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BootstrapResponse(idl.IdlStruct, typename="oarc_demo.BootstrapResponse"):
    client_id: str
    annotate.key("client_id")
    spatialdds_bootstrap: str
    dds_domain: types.int32
    cyclonedds_profile: str
    manifest_uris: types.sequence[str, 16]
    ttl_sec: types.uint32
    stamp: 'spatialdds_idl.oarc_demo.Time'


