"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: oarc_demo
  IDL file: oarc_demo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds_idl import oarc_demo

if TYPE_CHECKING:
    import builtin
    import spatial.argeo
    import spatial.common
    import spatial.core
    import spatial.disco
    import spatial.semantics
    import spatial.sensing.vision


MODULE_ID = "oarc.demo/1.7"
Time = types.typedef['spatialdds_idl.oarc_demo.Time', 'spatialdds_idl.builtin.Time']

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BootstrapQuery(idl.IdlStruct, typename="oarc_demo.BootstrapQuery"):
    client_id: str
    annotate.key("client_id")
    client_kind: str
    capabilities: types.sequence[str, 16]
    location_hint: str
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BootstrapResponse(idl.IdlStruct, typename="oarc_demo.BootstrapResponse"):
    client_id: str
    annotate.key("client_id")
    spatialdds_bootstrap: str
    dds_domain: types.int32
    cyclonedds_profile: str
    manifest_uris: types.sequence[str, 16]
    ttl_sec: types.uint32
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class QualityRequirements(idl.IdlStruct, typename="oarc_demo.QualityRequirements"):
    max_rmse_m: types.float64
    min_confidence: types.float64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class LocalizeQuality(idl.IdlStruct, typename="oarc_demo.LocalizeQuality"):
    success: bool
    confidence: types.float64
    rmse_m: types.float64


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VpsRequest(idl.IdlStruct, typename="oarc_demo.VpsRequest"):
    request_id: str
    annotate.key("request_id")
    service_id: str
    client_frame_ref: 'spatialdds_idl.spatial.common.FrameRef'
    prior_geopose: 'spatialdds_idl.spatial.core.GeoPose'
    vision_frame: 'spatialdds_idl.spatial.sensing.vision.VisionFrame'
    quality_requirements: 'spatialdds_idl.oarc_demo.QualityRequirements'
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class VpsResponse(idl.IdlStruct, typename="oarc_demo.VpsResponse"):
    request_id: str
    annotate.key("request_id")
    service_id: str
    node_geo: 'spatialdds_idl.spatial.argeo.NodeGeo'
    quality: 'spatialdds_idl.oarc_demo.LocalizeQuality'
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CatalogFilter(idl.IdlStruct, typename="oarc_demo.CatalogFilter"):
    kind_in: types.sequence[str, 16]


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CatalogQuery(idl.IdlStruct, typename="oarc_demo.CatalogQuery"):
    query_id: str
    annotate.key("query_id")
    reply_topic: str
    coverage: types.sequence['spatialdds_idl.spatial.disco.CoverageElement', 4]
    coverage_frame_ref: 'spatialdds_idl.spatial.common.FrameRef'
    has_filter: bool
    filter: 'spatialdds_idl.oarc_demo.CatalogFilter'
    limit: types.uint32
    page_token: str
    stamp: 'spatialdds_idl.oarc_demo.Time'
    ttl_sec: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CatalogEntry(idl.IdlStruct, typename="oarc_demo.CatalogEntry"):
    content_id: str
    kind: str
    name: str
    coverage: types.sequence['spatialdds_idl.spatial.disco.CoverageElement', 4]
    frame_ref: 'spatialdds_idl.spatial.common.FrameRef'
    formats: types.sequence[str, 8]
    updated_sec: types.uint64
    href: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class CatalogResponse(idl.IdlStruct, typename="oarc_demo.CatalogResponse"):
    query_id: str
    results: types.sequence['spatialdds_idl.oarc_demo.CatalogEntry', 256]
    next_page_token: str
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class DetectionWithVelocity(idl.IdlStruct, typename="oarc_demo.DetectionWithVelocity"):
    detection: 'spatialdds_idl.spatial.semantics.Detection3D'
    has_velocity: bool
    velocity: 'spatialdds_idl.spatial.common.Vec3'
    source_modality: str


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class OperatorDetectionSet(idl.IdlStruct, typename="oarc_demo.OperatorDetectionSet"):
    set_id: str
    annotate.key("set_id")
    source_operator: str
    frame_ref: 'spatialdds_idl.spatial.common.FrameRef'
    dets: types.sequence['spatialdds_idl.oarc_demo.DetectionWithVelocity', 256]
    frame_seq: types.uint64
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusedTrack(idl.IdlStruct, typename="oarc_demo.FusedTrack"):
    track_id: str
    annotate.key("track_id")
    position: 'spatialdds_idl.spatial.common.Vec3'
    velocity: 'spatialdds_idl.spatial.common.Vec3'
    position_uncertainty: types.float64
    object_class: str
    confidence: types.float64
    source_operators: types.sequence[str, 16]
    source_modalities: types.sequence[str, 16]
    source_count: types.uint32
    track_age: types.float64
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusedTrackSet(idl.IdlStruct, typename="oarc_demo.FusedTrackSet"):
    source_operator: str
    annotate.key("source_operator")
    tracks: types.sequence['spatialdds_idl.oarc_demo.FusedTrack', 256]
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class OperatorTrackCount(idl.IdlStruct, typename="oarc_demo.OperatorTrackCount"):
    operator_id: str
    track_count: types.uint32


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class FusionCoverage(idl.IdlStruct, typename="oarc_demo.FusionCoverage"):
    source_operator: str
    annotate.key("source_operator")
    track_count: types.uint32
    multi_source_count: types.uint32
    multi_source_pct: types.float64
    best_single_operator_count: types.uint32
    coverage_improvement: types.float64
    best_av_operator_count: types.uint32
    coverage_improvement_excl_infra: types.float64
    per_operator_track_count: types.sequence['spatialdds_idl.oarc_demo.OperatorTrackCount', 16]
    stamp: 'spatialdds_idl.oarc_demo.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class BlobChunk(idl.IdlStruct, typename="oarc_demo.BlobChunk"):
    blob_id: str
    annotate.key("blob_id")
    index: types.uint32
    annotate.key("index")
    total_chunks: types.uint32
    crc32: types.uint32
    data: types.sequence[types.uint8, 65535]


