#!/usr/bin/env python3
"""
Generate Python bindings for the bundled SpatialDDS IDL.

Runs ``idlc -l py`` over ``idl/v1.7/`` (the verbatim spec bundle) and
``idl/demo/`` (demo-owned structs for flows the spec has no type for), applies
the fixes idlc's Python backend needs, and writes an importable package.

Spec provenance
---------------

``idl/v1.7/`` is vendored verbatim from **SpatialDDS 1.7 (2026-08-23, tag
``v1.7``)** in ``OpenArCloud/SpatialDDS-spec``. Resync with::

    git -C ../SpatialDDS-spec archive v1.7 idl/v1.7 | tar -x -C .
    python3 scripts/generate_types.py --check

The pin is the **tag**, not a commit hash: ``v1.7`` is a stamped release and
will not move, so it says what this demo conforms to in a way a hash does
not.

**Do not track the spec repo's ``main``.** Main is the 1.8 draft, bootstrapped
from 1.7 and carrying unswept ``/1.7`` identifiers — resyncing from it would
silently mix draft 1.8 IDL into a demo that documents itself as 1.7
conformant, and the drift gate would pass because the generated output would
match whatever was vendored. This demo moves to 1.8 only under a deliberate
migration brief, the way it moved to each 1.7 revision.

The generated tree is checked in, so day-to-day work needs neither idlc nor
Docker. ``--check`` re-runs the generator into a temp directory and diffs, so
stale output is a test failure rather than a surprise.

    python3 scripts/generate_types.py            # regenerate in place
    python3 scripts/generate_types.py --check    # fail if checked-in output is stale

idlc is not usually installed on a host; run it in the demo image:

    docker run --rm -v "$PWD:/repo" -w /repo cyclonedds-python \\
        python3 scripts/generate_types.py

Post-processing (all of it here, never by hand-editing generated files):

1. **Bare union discriminators.** idlc emits ``discriminator=CovarianceType``
   as a bare name even when the enum lives in another module, so importing
   ``spatial.core`` dies with ``NameError: name 'CovarianceType' is not
   defined``. Other cross-module references are emitted as quoted forward refs
   and resolve lazily; the discriminator and its ``types.case[[...]]`` labels
   are evaluated when the class is created. We add the missing import.

2. **Package nesting.** idlc emits top-level ``spatial/`` and ``builtin/``
   packages. We nest them under one package so the repo exposes a single
   importable name, rewriting ``import spatial`` to bind the same local name.
   Quoted forward refs ("spatial.common.Mat3x3") resolve against module
   globals, so they keep working; ``typename="spatial.core.CovMatrix"`` is the
   DDS type identity and is deliberately left alone.
"""

from __future__ import annotations

import argparse
import filecmp
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC_IDL = REPO / "idl" / "v1.7"
DEMO_IDL = REPO / "idl" / "demo"
DEFAULT_OUT = REPO / "spatialdds_idl"

# Top-level packages idlc emits are discovered from its output rather than
# hardcoded, so adding an IDL module (e.g. idl/demo/) needs no change here.

HEADER = """# Generated by scripts/generate_types.py — do not edit.
# Regenerate with:  docker run --rm -v "$PWD:/repo" -w /repo cyclonedds-python \\
#                       python3 scripts/generate_types.py
"""


def find_idlc() -> str | None:
    idlc = os.environ.get("IDLC_PATH") or shutil.which("idlc")
    if idlc:
        return idlc
    for candidate in ("/usr/local/bin/idlc", "/opt/homebrew/bin/idlc"):
        if os.path.exists(candidate):
            return candidate
    return None


# Appendix E provisional profiles. They now live in `provisional/` rather
# than `examples/`, which is the distinction that matters: `examples/` holds
# informative design sketches (agent, neural), `provisional/` holds profiles
# with registered 3.3.2 type names that a deployment can build against.
# Globbed rather than named, so a new provisional profile is picked up.
PROVISIONAL_DIR = "provisional"


def idl_files() -> list[Path]:
    files = sorted(SPEC_IDL.glob("*.idl"))
    provisional = SPEC_IDL / PROVISIONAL_DIR
    if provisional.is_dir():
        files += sorted(provisional.glob("*.idl"))
    if DEMO_IDL.is_dir():
        files += sorted(DEMO_IDL.glob("*.idl"))
    if not files:
        raise SystemExit(f"no IDL found under {SPEC_IDL} or {DEMO_IDL}")
    return files


def run_idlc(idlc: str, out_dir: Path) -> None:
    """idlc's Python backend ignores -o and writes into cwd, so we chdir."""
    out_dir.mkdir(parents=True, exist_ok=True)
    includes = ["-I", str(SPEC_IDL), "-I", str(SPEC_IDL / PROVISIONAL_DIR)]
    if DEMO_IDL.is_dir():
        includes += ["-I", str(DEMO_IDL)]
    for path in idl_files():
        result = subprocess.run(
            [idlc, "-l", "py", *includes, str(path)],
            cwd=out_dir, capture_output=True, text=True,
        )
        if result.returncode != 0:
            raise SystemExit(
                f"idlc failed on {path.name}:\n{result.stdout}\n{result.stderr}"
            )


def _defined_names(source: str) -> set[str]:
    return set(re.findall(r"^class (\w+)", source, re.M))


def _index_definitions(root: Path, package: str) -> dict[str, str]:
    """Map each generated class name to the importable module that defines it."""
    index: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        parts = path.relative_to(root).with_suffix("").parts
        module = ".".join((package, *parts))
        for name in _defined_names(path.read_text()):
            index.setdefault(name, module)
    return index


def fix_union_discriminators(root: Path, package: str) -> list[str]:
    """
    Import union discriminators that idlc emitted as unresolvable bare names.

    Runs after nesting, so the imports it writes use the final package path.
    """
    index = _index_definitions(root, package)
    fixed: list[str] = []
    for path in sorted(root.rglob("*.py")):
        source = path.read_text()
        names = set(re.findall(r"discriminator=(\w+)", source))
        missing = [n for n in names if n not in _defined_names(source)]
        if not missing:
            continue
        imports = []
        for name in sorted(missing):
            module = index.get(name)
            if module is None:
                raise SystemExit(
                    f"{path}: union discriminator {name!r} is undefined and no "
                    "generated module defines it — cannot patch, report instead"
                )
            imports.append(f"from {module} import {name}")
            fixed.append(f"{path.relative_to(root)}: {name} <- {module}")
        # Place the imports after the generated import block, before first use.
        anchor = "import cyclonedds.idl.types as types\n"
        if anchor not in source:
            raise SystemExit(f"{path}: unexpected generated layout, cannot patch")
        source = source.replace(
            anchor,
            anchor + "\n# generate_types.py: idlc emits this discriminator as a bare name\n"
            + "\n".join(imports) + "\n",
            1,
        )
        path.write_text(source)
    return fixed


def fix_python_keyword_fields(root: Path) -> dict[str, dict[str, str]]:
    """
    Rename fields whose IDL name is a Python keyword, preserving the wire name.

    The spec legitimately uses ``global`` (CoverageElement, sensing common) and
    ``from`` (Transform, ValidityWindow) as field names.

    idlc >= 11 handles this itself, emitting ``_global`` / ``_from``; we only
    record the mapping. idlc 0.10.5 emits them verbatim, so the module is a
    SyntaxError and cannot be imported at all — and that version also lacks
    ``annotate.member_name``, so it cannot be repaired faithfully. See the
    toolchain note in the module docstring.

    The fix is the escape cyclonedds provides: rename the Python attribute to
    ``<name>_`` and restore the declared name with
    ``@annotate.member_name("<name>_", "<name>")``. Wire identity is preserved —
    these structs carry ``@annotate.autoid("sequential")``, so member IDs come
    from declaration order rather than from names, and member_name puts the
    spec's name back in the type metadata.

    Returns {typename: {python_name: wire_name}} so JSON-facing code can emit
    spec field names.
    """
    import keyword

    aliases: dict[str, dict[str, str]] = {}
    field_re = re.compile(r"^(    )(\w+)(\s*:\s.*)$")
    class_re = re.compile(r'^class (\w+)\(.*typename="([^"]+)"')

    for path in sorted(root.rglob("*.py")):
        original = path.read_text()
        out: list[str] = []
        typename: str | None = None
        renamed: dict[str, str] = {}

        for line in original.splitlines():
            m = class_re.match(line)
            if m:
                typename = m.group(2)
                out.append(line)
                continue
            f = field_re.match(line)
            if f and typename and f.group(2).startswith("_") and keyword.iskeyword(f.group(2)[1:]):
                # idlc >= 11 already dodges Python keywords by prefixing an
                # underscore. Nothing to rewrite; just record the mapping so
                # JSON-facing code can emit the spec's field name.
                aliases.setdefault(typename, {})[f.group(2)] = f.group(2)[1:]
                out.append(line)
                continue
            if f and keyword.iskeyword(f.group(2)) and typename:
                name = f.group(2)
                out.append(f"{f.group(1)}{name}_{f.group(3)}")
                # cyclonedds applies field annotations inside the class body,
                # immediately after the field they describe.
                out.append(
                    f'{f.group(1)}annotate.member_name("{name}_", "{name}")'
                )
                renamed[f"{name}_"] = name
                aliases.setdefault(typename, {})[f"{name}_"] = name
                continue
            out.append(line)

        new_source = "\n".join(out) + "\n"
        if new_source != original:
            path.write_text(new_source)
    return aliases


def write_field_aliases(out_dir: Path, aliases: dict[str, dict[str, str]]) -> None:
    """Record the keyword renames so JSON-facing code can use spec names."""
    lines = [
        HEADER,
        '"""Python attribute -> IDL field name, for fields renamed to dodge',
        'Python keywords. See fix_python_keyword_fields in the generator."""',
        "",
        "FIELD_ALIASES = {",
    ]
    for typename in sorted(aliases):
        lines.append(f'    "{typename}": {{')
        for py, wire in sorted(aliases[typename].items()):
            lines.append(f'        "{py}": "{wire}",')
        lines.append("    },")
    lines += ["}", "", "",
              "def wire_name(typename: str, attr: str) -> str:",
              '    """The IDL field name for a generated attribute."""',
              "    return FIELD_ALIASES.get(typename, {}).get(attr, attr)", ""]
    (out_dir / "_field_aliases.py").write_text("\n".join(lines))


def nest_packages(staging: Path, out_dir: Path, package: str) -> None:
    """Move idlc's top-level packages under one package and fix their imports."""
    out_dir.mkdir(parents=True, exist_ok=True)
    roots = sorted(
        d.name for d in staging.iterdir()
        if d.is_dir() and (d / "__init__.py").exists()
    )
    if not roots:
        raise SystemExit(f"idlc produced no packages in {staging}")

    for root in roots:
        shutil.move(str(staging / root), str(out_dir / root))

    import_re = re.compile(r"^import (%s)$" % "|".join(roots), re.M)
    # Quoted forward refs ('spatial.common.Mat3x3'). cyclonedds resolves these
    # with import_module() on the absolute path, NOT against module globals, so
    # nesting means they have to be rewritten too. Single quotes distinguish
    # them from typename="spatial.core.CovMatrix", which is the DDS type
    # identity and must survive untouched.
    ref_re = re.compile(r"'(%s)\." % "|".join(roots))
    for path in sorted(out_dir.rglob("*.py")):
        source = path.read_text()
        patched = import_re.sub(rf"from {package} import \1", source)
        patched = ref_re.sub(rf"'{package}.\1.", patched)
        if patched != source:
            path.write_text(patched)

    (out_dir / "__init__.py").write_text(
        HEADER
        + '"""Generated SpatialDDS 1.7 types. See scripts/generate_types.py."""\n\n'
        + "".join(f"from . import {r}\n" for r in roots)
        + "\n__all__ = [%s]\n" % ", ".join(f'"{r}"' for r in roots)
    )


def generate(out_dir: Path, package: str) -> list[str]:
    idlc = find_idlc()
    if not idlc:
        raise SystemExit(
            "idlc not found. Run inside the demo image:\n"
            '  docker run --rm -v "$PWD:/repo" -w /repo cyclonedds-python '
            "python3 scripts/generate_types.py"
        )
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp) / "staging"
        run_idlc(idlc, staging)
        if out_dir.exists():
            shutil.rmtree(out_dir)
        # Nest first: the discriminator imports must name the final package.
        nest_packages(staging, out_dir, package)
        fixed = fix_union_discriminators(out_dir, package)
        aliases = fix_python_keyword_fields(out_dir)
        write_field_aliases(out_dir, aliases)
        for typename in sorted(aliases):
            for py, wire in sorted(aliases[typename].items()):
                fixed.append(f"{typename}: {wire} -> {py} (+member_name)")
    return fixed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in output differs from a fresh run")
    args = parser.parse_args()
    package = args.out.name

    if not args.check:
        fixed = generate(args.out, package)
        print(f"generated {args.out.relative_to(REPO)}")
        for line in fixed:
            print(f"  patched discriminator: {line}")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / package
        generate(fresh, package)

        # Comparing output from two different idlc versions says nothing about
        # whether the checked-in tree is stale — they differ in header and
        # import order regardless. Report that distinctly (exit 2) so callers
        # can tell "wrong toolchain" from "needs regenerating".
        checked_in_v = toolchain_version(args.out) if args.out.exists() else None
        fresh_v = toolchain_version(fresh)
        if checked_in_v and fresh_v and checked_in_v != fresh_v:
            print(
                f"toolchain mismatch: checked-in output was generated by idlc "
                f"{checked_in_v}, local idlc is {fresh_v}.\n"
                f"The canonical toolchain is the demo image (cyclonedds "
                f"{checked_in_v}); drift cannot be judged from here."
            )
            return 2

        diff = _tree_diff(args.out, fresh)
        if diff:
            print("Generated types are stale. Regenerate with:")
            print('  docker run --rm -v "$PWD:/repo" -w /repo cyclonedds-python \\')
            print("      python3 scripts/generate_types.py")
            for line in diff:
                print(f"  {line}")
            return 1
    print("generated types are up to date")
    return 0


TOOLCHAIN_RE = re.compile(r"Cyclone DDS IDL version:\s*(\S+)")


def toolchain_version(root: Path) -> str | None:
    """The idlc version recorded in a generated tree's headers."""
    for path in sorted(root.rglob("*.py")):
        m = TOOLCHAIN_RE.search(path.read_text())
        if m:
            return m.group(1)
    return None


def _tree_diff(a: Path, b: Path) -> list[str]:
    if not a.exists():
        return [f"missing: {a}"]
    def sources(root: Path) -> set:
        # Compare generated source only. __pycache__ appears as soon as anything
        # imports the package and says nothing about generator drift.
        return {
            p.relative_to(root) for p in root.rglob("*")
            if p.is_file() and "__pycache__" not in p.parts and p.suffix != ".pyc"
        }

    out: list[str] = []
    a_files = sources(a)
    b_files = sources(b)
    for only in sorted(a_files - b_files):
        out.append(f"unexpected file: {only}")
    for only in sorted(b_files - a_files):
        out.append(f"missing file: {only}")
    for shared in sorted(a_files & b_files):
        if not filecmp.cmp(a / shared, b / shared, shallow=False):
            out.append(f"differs: {shared}")
    return out


if __name__ == "__main__":
    sys.exit(main())
