// SPDX-License-Identifier: MIT
// SpatialDDS Convenience Aggregator (v1.7)
//
// The official v1.7 IDL lives under idl/v1.7/*.idl in this repository.
// This wrapper simply includes the individual profile files so existing
// build scripts that expect a single IDL can continue to function.

#include "idl/v1.7/types.idl"
#include "idl/v1.7/common.idl"
#include "idl/v1.7/core.idl"
#include "idl/v1.7/discovery.idl"
#include "idl/v1.7/anchors.idl"
#include "idl/v1.7/vision.idl"
#include "idl/v1.7/vio.idl"
#include "idl/v1.7/slam_frontend.idl"
#include "idl/v1.7/argeo.idl"
#include "idl/v1.7/lidar.idl"
#include "idl/v1.7/rad.idl"
#include "idl/v1.7/semantics.idl"
