"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: oarc_model
  IDL file: oarc_model.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
from spatialdds_idl import oarc_model

if TYPE_CHECKING:
    import builtin
    import spatial.common
    import spatial.core


MODULE_ID = "oarc.model/0.1"
Time = types.typedef['spatialdds_idl.oarc_model.Time', 'spatialdds_idl.builtin.Time']
@annotate.final
class ModelLayer(idl.IdlEnum, typename="oarc_model.ModelLayer", default="STATIC"):
    STATIC = 0
    SLOW = 1
    FAST = 2
@annotate.final
class Basis(idl.IdlEnum, typename="oarc_model.Basis", default="OBSERVED"):
    OBSERVED = 0
    DECLARED = 1
    AUTHORED = 2
    DERIVED = 3
@annotate.final
class LifecycleState(idl.IdlEnum, typename="oarc_model.LifecycleState", default="ACTIVE"):
    ACTIVE = 0
    UNOBSERVED = 1
    RETIRED = 2
    SUPERSEDED = 3

@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Entity(idl.IdlStruct, typename="oarc_model.Entity"):
    entity_id: str
    annotate.key("entity_id")
    basis: 'spatialdds_idl.oarc_model.Basis'
    type_uris: types.sequence[str, 4]
    layer: 'spatialdds_idl.oarc_model.ModelLayer'
    frame_ref: 'spatialdds_idl.spatial.common.FrameRef'
    has_pose: bool
    pose: 'spatialdds_idl.spatial.core.PoseSE3'
    has_extent: bool
    extent: 'spatialdds_idl.spatial.core.Aabb3'
    properties: types.sequence['spatialdds_idl.spatial.common.KV', 32]
    external_refs: types.sequence['spatialdds_idl.spatial.common.KV', 8]
    content_refs: types.sequence[str, 8]
    state: 'spatialdds_idl.oarc_model.LifecycleState'
    state_reason: str
    source_id: str
    stamp: 'spatialdds_idl.oarc_model.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class Relationship(idl.IdlStruct, typename="oarc_model.Relationship"):
    rel_id: str
    annotate.key("rel_id")
    kind: str
    from_entity_id: str
    to_entity_id: str
    properties: types.sequence['spatialdds_idl.spatial.common.KV', 16]
    source_id: str
    stamp: 'spatialdds_idl.oarc_model.Time'


@dataclass
@annotate.appendable
@annotate.autoid("sequential")
class ModelCommand(idl.IdlStruct, typename="oarc_model.ModelCommand"):
    command_id: str
    annotate.key("command_id")
    verb: str
    entity_id: str
    reason: str
    requester_id: str
    has_pose: bool
    pose: 'spatialdds_idl.spatial.core.PoseSE3'
    stamp: 'spatialdds_idl.oarc_model.Time'


